library constants;

const String enterCity = "Enter City";
const String hourlyForecast = "Hourly Forecst";
const String currentCondition = "Current Condition";
const String tenDayForeCast = "10-Day Forecast";
const String humidity = "Humidity";
const String wind = "Wind";
const String aqi = "Air Quality (PM25)";
const String pressure = "Pressure";
const String uvIndex = "UV Index";
const String sunriseSunset = "Sunrise & Sunset";
const String feelsLike = "Feels Like";
const String precip = "Precip";
const String pleaseEnter = "Please Enter";
const String placeSearch = "place to search";
const String setting = "Setting";
const String toggleTheme = "Toggle Theme";
const String swichTheme = "Change to dark mode";
const String swichThemeLight = "Change to light mode";
